organization := "net.proofpeer"
name := "metis"
version := "0.2-SNAPSHOT"
scalaVersion := "2.11.6"
scalacOptions += "-feature"
libraryDependencies += "org.scalaz" %% "scalaz-core" % "latest.integration"
libraryDependencies += "org.scalatest" %% "scalatest" % "latest.integration"
